package JavaCool303;
import java.awt.*;

/**
 * <h1> Cool303Theme </h1><br>
 * <b>File Name:</b> Cool303Theme.java<br>
 * <b>Purpose:</b> Interface for the theme strategy; implement these methods for
 * a new theme strategy. For the getPreferredSize methods, return a <i>new Dimension</i>
 * object that will be the preferred size of that JObject. In the paint methods, customize
 * each element as you wish (refer to Pastel.java or Summer.java for an example).<br>
 * <b>File I/O:</b> No files are required or generated by the application<br>
 * @author Sheldon Benard
 */


public interface Cool303Theme {
    Dimension getButtonPreferredSize();
    Dimension getTextFieldPreferredSize();
    Dimension getContainerPreferredSize();
    void paintButton(Cool303Button button,Graphics g);
    void paintTextField(Cool303TextField textField, Graphics g);
    void paintContainer(Cool303Container container, Graphics g);
}
