package JavaCool303;
/**
 * <h1> Cool303Component </h1><br>
 * <b>File Name:</b> Cool303Component.java<br>
 * <b>Purpose:</b> Define Cool303Component interface. Each component will need to set a Cool303Theme<br>
 * <b>File I/O:</b> No files are required or generated by the application<br>
 * @author Sheldon Benard
 */
public interface Cool303Component {
    void setTheme(Cool303Theme theme);
}
