package JavaCool303;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * <h1>Cool303Button</h1>
 * <b>File Name:</b> Cool303Button.java<br>
 * <b>Purpose:</b> Implement Cool303Button component <br>
 * <b>File I/O:</b> No files are required or generated by the application
 * @author Sheldon Benard
 */
public class Cool303Button extends JButton implements Cool303Component{
    private Cool303Theme theme;
    private String text;

    /**
     * <b>Name:</b> Cool303Button<br>
     * <b>Purpose:</b> Cool303Button constructor; provide text for the button text label<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param text String representing button label
     */
    public Cool303Button(String text){
        super(text);
        this.setText(text);
        actionListener();
    }

    /**
     * <b>Name:</b> setText<br>
     * <b>Purpose:</b> setText for button<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param text String button label
     */
    @Override
    public void setText(String text) {
        this.text = text;
    }

    //set actionlistener to print text to console
    private void actionListener(){
        this.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println(text);
            }
        });
    }

    /**
     * <b>Name:</b> getText<br>
     * <b>Purpose:</b> getText for button<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @return String, button's label
     */
    public String getText(){return this.text;}

    /**
     * <b>Name:</b> setTheme<br>
     * <b>Purpose:</b> setTheme for button and adjust preferred size<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param theme Cool303Theme
     */
    public void setTheme(Cool303Theme theme) {
        this.theme = theme;
        this.setPreferredSize(theme.getButtonPreferredSize());
    }

    /**
     * <b>Name:</b> paintComponent<br>
     * <b>Purpose:</b> Override paintComponent<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param g Graphics used to paint component
     */
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(theme != null)
            theme.paintButton(this,g);
        this.repaint();
        this.revalidate();

    }


}
