package JavaCool303;
import javax.swing.*;
import java.awt.*;

/**
 * <h1>Cool303TextField</h1>
 * <b>File Name:</b> Cool303TextField.java<br>
 * <b>Purpose:</b> Implement Cool303TextField component <br>
 * <b>File I/O:</b> No files are required or generated by the application
 * @author Sheldon Benard
 */
public class Cool303TextField extends JTextField implements Cool303Component{
    private Cool303Theme theme; //theme field; used in paintComponent override

    /**
     * <b>Name:</b> Cool303TextField<br>
     * <b>Purpose:</b> Cool303TextField constructor; provide text for the textfield<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param text String representing textFields text
     */
    public Cool303TextField(String text){ this.setText(text);}

    /**
     * <b>Name:</b> setTheme<br>
     * <b>Purpose:</b> setTheme for text field and adjust preferred size<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param theme Cool303Theme
     */
    public void setTheme(Cool303Theme theme) {
        this.theme = theme;
        this.setPreferredSize(theme.getTextFieldPreferredSize());
    }
    /**
     * <b>Name:</b> paintComponent<br>
     * <b>Purpose:</b> Override paintComponent<br>
     * <b>Author:</b> Sheldon Benard<br>
     * @param g Graphics used to paint component
     */
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(theme != null)
            theme.paintTextField(this,g);
        this.repaint();
        this.revalidate();
    }

}
